version: '3'
services:
  web:
    build: .
    command: mix phx.server
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - redis

  redis:
    image: redis:3.2
    volumes:
      - /data
    command: [redis-server, --appendonly, 'yes']
